### ISSUE TITLE
Fix "Similar code" issue in js/index.js

### ISSUE THREAD

**Issue by 808dkaneohe** [CSGOFlair/dev#32]
Similar code found in 1 other location (mass = 114)

https://codeclimate.com/github/CSGOFlair/dev/js/index.js#issue_5811178500aa1600010000b2

**Comment by SirFrancisBillard** [comment]
This is a really stupid issue that should not be fixed and does not need to be fixed.

**Comment by 808dkaneohe** [comment]
ik


GitHub: github.com/808dkaneohe

When life gives you lemons you probably just found lemons, when life gets
you down make a comforter. -Bo Burnham

-Diego  deann21@punahou.edu ;o ⍥
∂ˆ´©ø ´å˜㉱⦘:)
