### ISSUE TITLE
Lovely HD banner

### ISSUE THREAD

**Issue by SirFrancisBillard** [CSGOFlair/dev#6]
bleh

**Comment by 808dkaneohe** [comment]
![nick-young-confused-face-300x256_nqlyaa](https://cloud.githubusercontent.com/assets/14227413/23815094/809312f2-058a-11e7-8773-f22223dae56c.jpg)

**Comment by irefl** [comment]
@SirFrancisBillard please see our guide to making issues in CONTRIBUTING.md

**Comment by SirFrancisBillard** [comment]
funny joke

**Comment by irefl** [comment]
@SirFrancisBillard Delete account please
